# User Settings | Edit there as per required

title: Alireza Hayati
url: "https://alireza.one"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    Alireza <span class="faded">'s blog</span>

email: alirezahayati@outlook.com
author: Alireza Hayati
# This description will show up in google search results
# (for index page) etc.
description: >
    Sharing ideas about technology, user experience and internet.

# This will what will show against &copy; in the footer
copyright: :)
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>Alireza Hayati</span>, Senior UX analyst and administrative automation mentor. I give simple methods for intricate problems.

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Senior User Experience designer and analyst. Organizer at HCF. 

about_footer: true

twitter_username: alrrza
github_username: alirezahy
facebook_id: alrrza

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-79268993-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/logo-placeholder.png" # This will show in facebook thumbnails
twitter_image: "images/logo-placeholder.png" # This will show in twitter cards



markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
